[package]
name = "texpack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lz4 = "1.23.2"
xml-rs = "0.8.4"
anyhow = "1.0.52"
png = "0.17.3"